<table>
  <tr>
    <td colspan="2" rowspan="2" bgcolor="purple"><div align="center" style='color:white'>No</div></td>
    <td colspan="3" rowspan="2" bgcolor="purple"><div align="center" style='color:white'><strong>Keterangan</strong></div>
      <div align="center" style='color:white'></div>      <div align="center" style='color:white'></div>
      <div align="center" style='color:white'></div>      <div align="center" style='color:white'></div></td>
    <td colspan="2" bgcolor="purple"><div align="center" style='color:white'><strong>UMUM</strong></div></td>
    <td colspan="2" bgcolor="purple"><div align="center" style='color:white'><strong>BPJS</strong></div></td>
    <td colspan="2" bgcolor="purple"><div align="center" style='color:white'><strong> KARTU SEHAT</strong></div></td>
    </tr>
  <tr>
    <td width="80" bgcolor="purple"><div align="center" style='color:white'><strong>L</strong></div></td>
    <td width="80" bgcolor="purple"><div align="center" style='color:white'><strong>P</strong></div></td>
    <td width="80" bgcolor="purple"><div align="center" style='color:white'><strong>L</strong></div></td>
    <td width="80" bgcolor="purple"><div align="center" style='color:white'><strong>P</strong></div></td>
    <td width="80" bgcolor="purple"><div align="center" style='color:white'><strong>L</strong></div></td>
    <td width="80" bgcolor="purple"><div align="center" style='color:white'><strong>P</strong></div></td>
  </tr>
  <tr>
    <td width="18">&nbsp;</td>
    <td width="18" align="top">1.</td>
    <td width="700">  Jumlah pemeriksaan lab. yang dilakukan di laboratorium Puskesmas</td>
    <td width="10"></td>
    <td width="12">:</td>
    <td width="80"><input id="S30000562ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000562ul"       name="detail[G01_001][data_val][]" value="<?php echo $G01_001['data_val0']; ?>" size="12" /></td>
    <td width="80"><input id="S30000562up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000562up"       name="detail[G01_001][data_val][]" value="<?php echo $G01_001['data_val1']; ?>" size="12" /></td>
    <td width="80"><input id="S30000562bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000562bl"       name="detail[G01_001][data_val][]" value="<?php echo $G01_001['data_val2']; ?>" size="12" /></td>
    <td width="80"><input id="S30000562bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000562bp"       name="detail[G01_001][data_val][]" value="<?php echo $G01_001['data_val3']; ?>" size="12" /></td>
    <td width="80"><input id="S30000562kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000562kl"       name="detail[G01_001][data_val][]" value="<?php echo $G01_001['data_val4']; ?>" size="12" /></td>
    <td width="80"><input id="S30000562kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000562kp"       name="detail[G01_001][data_val][]" value="<?php echo $G01_001['data_val5']; ?>" size="12" /></td>
  </tr>                                                                                                                     
 <tr>                                                                                                                       
   <td width="18">&nbsp;</td>                                                                                               
    <td width="18">2</td>                                                                                                   
    <td width="454"> Jumlah darah trombosit tersangka DBD</td>                                                              
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000564ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000564ul"                  name="detail[G01_002][data_val][]" value="<?php echo $G01_002['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000564up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000564up"                  name="detail[G01_002][data_val][]" value="<?php echo $G01_002['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000564bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000564bl"                  name="detail[G01_002][data_val][]" value="<?php echo $G01_002['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000564bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000564bp"                  name="detail[G01_002][data_val][]" value="<?php echo $G01_002['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000564kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000564kl"                  name="detail[G01_002][data_val][]" value="<?php echo $G01_002['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000564kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000564kp"                  name="detail[G01_002][data_val][]" value="<?php echo $G01_002['data_val5']; ?>" size="12" /></td>
 </tr>                                                                                                                      
   <tr>                                                                                                                     
     <td width="18">&nbsp;</td>                                                                                             
    <td width="18">3</td>                                                                                                   
    <td width="454">  Jumlah pemeriksaan darah malaria</td>                                                                 
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000565ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000565ul"                  name="detail[G01_003][data_val][]" value="<?php echo $G01_003['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000565up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000565up"                  name="detail[G01_003][data_val][]" value="<?php echo $G01_003['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000565bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000565bl"                  name="detail[G01_003][data_val][]" value="<?php echo $G01_003['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000565bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000565bp"                  name="detail[G01_003][data_val][]" value="<?php echo $G01_003['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000565kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000565kl"                  name="detail[G01_003][data_val][]" value="<?php echo $G01_003['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000565kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000565kp"                  name="detail[G01_003][data_val][]" value="<?php echo $G01_003['data_val5']; ?>" size="12" /></td>
   </tr> <tr>                                                                                                               
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">4</td>                                                                                                   
    <td width="454"> Jumlah pemeriksaan darah malaria positif</td>                                                          
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000566ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000566ul"                  name="detail[G01_004][data_val][]" value="<?php echo $G01_004['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000566up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000566up"                  name="detail[G01_004][data_val][]" value="<?php echo $G01_004['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000566bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000566bl"                  name="detail[G01_004][data_val][]" value="<?php echo $G01_004['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000566bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000566bp"                  name="detail[G01_004][data_val][]" value="<?php echo $G01_004['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000566kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000566kl"                  name="detail[G01_004][data_val][]" value="<?php echo $G01_004['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000566kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000566kp"                  name="detail[G01_004][data_val][]" value="<?php echo $G01_004['data_val5']; ?>" size="12" /></td>
   </tr> <tr>                                                                                                              
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">5</td>                                                                                                   
    <td width="454">  Jumlah pemeriksaan test kehamilan</td>                                                                
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000567ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000567ul"                  name="detail[G01_005][data_val][]" value="<?php echo $G01_005['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000567up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000567up"                  name="detail[G01_005][data_val][]" value="<?php echo $G01_005['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000567bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000567bl"                  name="detail[G01_005][data_val][]" value="<?php echo $G01_005['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000567bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000567bp"                  name="detail[G01_005][data_val][]" value="<?php echo $G01_005['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000567kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000567kl"                  name="detail[G01_005][data_val][]" value="<?php echo $G01_005['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000567kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000567kp"                  name="detail[G01_005][data_val][]" value="<?php echo $G01_005['data_val5']; ?>" size="12" /></td>
   </tr> <tr>                                                                                                               
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">6</td>                                                                                                   
    <td width="454">  Jumlah pemeriksaan sputum TB</td>                                                                     
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000568ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000568ul"                  name="detail[G01_006][data_val][]" value="<?php echo $G01_006['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000568up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000568up"                  name="detail[G01_006][data_val][]" value="<?php echo $G01_006['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000568bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000568bl"                  name="detail[G01_006][data_val][]" value="<?php echo $G01_006['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000568bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000568bp"                  name="detail[G01_006][data_val][]" value="<?php echo $G01_006['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000568kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000568kl"                  name="detail[G01_006][data_val][]" value="<?php echo $G01_006['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000568kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000568kp"                  name="detail[G01_006][data_val][]" value="<?php echo $G01_006['data_val5']; ?>" size="12" /></td>
   </tr> <tr>                                                                                                               
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">7</td>                                                                                                   
    <td width="454"> Jumlah pemeriksaan Urine Protein pada Ibu hamil</td>                                                   
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000569ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000569ul"                  name="detail[G01_007][data_val][]" value="<?php echo $G01_007['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000569up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000569up"                  name="detail[G01_007][data_val][]" value="<?php echo $G01_007['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000569bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000569bl"                  name="detail[G01_007][data_val][]" value="<?php echo $G01_007['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000569bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000569bp"                  name="detail[G01_007][data_val][]" value="<?php echo $G01_007['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000569kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000569kl"                  name="detail[G01_007][data_val][]" value="<?php echo $G01_007['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000569kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000569kp"                  name="detail[G01_007][data_val][]" value="<?php echo $G01_007['data_val5']; ?>" size="12" /></td>
   </tr>                                                                                                                    
  <tr>                                                                                                                      
    <td>&nbsp;</td>                                                                                                         
    <td>8</td>                                                                                                              
    <td>Jumlah pemeriksaan Telur Cacing murid SD</td>                                                                       
    <td></td>                                                                                                               
    <td>:</td>                                                                                                              
    <td><input id="S30000737ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737ul"                  name="detail[G01_008][data_val][]" value="<?php echo $G01_008['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000737up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737up"                  name="detail[G01_008][data_val][]" value="<?php echo $G01_008['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000737bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737bl"                  name="detail[G01_008][data_val][]" value="<?php echo $G01_008['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000737bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737bp"                  name="detail[G01_008][data_val][]" value="<?php echo $G01_008['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000737kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737kl"                  name="detail[G01_008][data_val][]" value="<?php echo $G01_008['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000737kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737kp"                  name="detail[G01_008][data_val][]" value="<?php echo $G01_008['data_val5']; ?>" size="12" /></td>
  </tr>                                                                                                                     
  <tr>                                                                                                                      
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">9</td>                                                                                                   
    <td width="454"> Jumlah pemeriksaan IMS</td>                                                                            
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000570ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000570ul"                  name="detail[G01_009][data_val][]" value="<?php echo $G01_009['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000570up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000570up"                  name="detail[G01_009][data_val][]" value="<?php echo $G01_009['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000570bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000570bl"                  name="detail[G01_009][data_val][]" value="<?php echo $G01_009['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000570bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000570bp"                  name="detail[G01_009][data_val][]" value="<?php echo $G01_009['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000570kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000570kl"                  name="detail[G01_009][data_val][]" value="<?php echo $G01_009['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000570kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000570kp"                  name="detail[G01_009][data_val][]" value="<?php echo $G01_009['data_val5']; ?>" size="12" /></td>
  </tr> <tr>                                                                                                                
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">10</td>                                                                                                  
    <td width="454"> Jumlah pemeriksaan HIV</td>                                                                            
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000571ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000571ul"                  name="detail[G01_010][data_val][]" value="<?php echo $G01_010['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000571up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000571up"                  name="detail[G01_010][data_val][]" value="<?php echo $G01_010['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000571bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000571bl"                  name="detail[G01_010][data_val][]" value="<?php echo $G01_010['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000571bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000571bp"                  name="detail[G01_010][data_val][]" value="<?php echo $G01_010['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000571kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000571kl"                  name="detail[G01_010][data_val][]" value="<?php echo $G01_010['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000571kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000571kp"                  name="detail[G01_010][data_val][]" value="<?php echo $G01_010['data_val5']; ?>" size="12" /></td>
  </tr> <tr>                                                                                                                
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">11</td>                                                                                                  
    <td width="454"> Jumlah pemeriksaan positif HIV</td>                                                                    
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000572ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000572ul"                  name="detail[G01_011][data_val][]" value="<?php echo $G01_011['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000572up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000572up"                  name="detail[G01_011][data_val][]" value="<?php echo $G01_011['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000572bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000572bl"                  name="detail[G01_011][data_val][]" value="<?php echo $G01_011['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000572bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000572bp"                  name="detail[G01_011][data_val][]" value="<?php echo $G01_011['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000572kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000572kl"                  name="detail[G01_011][data_val][]" value="<?php echo $G01_011['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000572kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000572kp"                  name="detail[G01_011][data_val][]" value="<?php echo $G01_011['data_val5']; ?>" size="12" /></td>
  </tr> <tr>                                                                                                                
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">12</td>                                                                                                  
    <td width="454">Jumlah pemeriksaan NS1/DBD</td>                                                                         
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000574ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000574ul"                  name="detail[G01_012][data_val][]" value="<?php echo $G01_012['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000574up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000574up"                  name="detail[G01_012][data_val][]" value="<?php echo $G01_012['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000574bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000574bl"                  name="detail[G01_012][data_val][]" value="<?php echo $G01_012['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000574bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000574bp"                  name="detail[G01_012][data_val][]" value="<?php echo $G01_012['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000574kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000574kl"                  name="detail[G01_012][data_val][]" value="<?php echo $G01_012['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000574kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000574kp"                  name="detail[G01_012][data_val][]" value="<?php echo $G01_012['data_val5']; ?>" size="12" /></td>
  </tr>                                                                                                                     
  <tr>                                                                                                                      
    <td>&nbsp;</td>                                                                                                         
    <td>13</td>                                                                                                             
    <td>Jumlah pemeriksaan HB</td>                                                                                          
    <td></td>                                                                                                               
    <td>:</td>                                                                                                              
    <td><input id="S30000734ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000734ul"                  name="detail[G01_013][data_val][]" value="<?php echo $G01_013['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000734up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000734up"                  name="detail[G01_013][data_val][]" value="<?php echo $G01_013['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000734bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000734bl"                  name="detail[G01_013][data_val][]" value="<?php echo $G01_013['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000734bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000734bp"                  name="detail[G01_013][data_val][]" value="<?php echo $G01_013['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000734kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000734kl"                  name="detail[G01_013][data_val][]" value="<?php echo $G01_013['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000734kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000734kp"                  name="detail[G01_013][data_val][]" value="<?php echo $G01_013['data_val5']; ?>" size="12" /></td>
  </tr>                                                                                                                     
  <tr>                                                                                                                      
    <td>&nbsp;</td>                                                                                                         
    <td>14</td>                                                                                                             
    <td>Jumlah pemeriksaan Leukosit</td>                                                                                    
    <td></td>                                                                                                               
    <td>:</td>                                                                                                              
    <td><input id="S30000735ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000735ul"                  name="detail[G01_014][data_val][]" value="<?php echo $G01_014['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000735up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000735up"                  name="detail[G01_014][data_val][]" value="<?php echo $G01_014['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000735bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000735bl"                  name="detail[G01_014][data_val][]" value="<?php echo $G01_014['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000735bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000735bp"                  name="detail[G01_014][data_val][]" value="<?php echo $G01_014['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000735kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000735kl"                  name="detail[G01_014][data_val][]" value="<?php echo $G01_014['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000735kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000735kp"                  name="detail[G01_014][data_val][]" value="<?php echo $G01_014['data_val5']; ?>" size="12" /></td>
  </tr>                                                                                                                     
  <tr>                                                                                                                      
    <td>&nbsp;</td>                                                                                                         
    <td>15</td>                                                                                                             
    <td>Jumlah pemeriksaan Gol darah</td>                                                                                   
    <td></td>                                                                                                               
    <td>:</td>                                                                                                              
    <td><input id="S30000736ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000736ul"                  name="detail[G01_015][data_val][]" value="<?php echo $G01_015['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000736up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000736up"                  name="detail[G01_015][data_val][]" value="<?php echo $G01_015['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000736bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000736bl"                  name="detail[G01_015][data_val][]" value="<?php echo $G01_015['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000736bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000736bp"                  name="detail[G01_015][data_val][]" value="<?php echo $G01_015['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000736kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000736kl"                  name="detail[G01_015][data_val][]" value="<?php echo $G01_015['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000736kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000736kp"                  name="detail[G01_015][data_val][]" value="<?php echo $G01_015['data_val5']; ?>" size="12" /></td>
  </tr>                                                                                                                     
  <tr>                                                                                                                      
    <td width="18">&nbsp;</td>                                                                                              
    <td width="18">16</td>                                                                                                  
    <td width="454">Jumlah pemeriksaan Hematokrit</td>                                                                      
    <td width="10"></td>                                                                                                    
    <td width="12">:</td>                                                                                                   
    <td><input id="S30000737ul" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737ul"                  name="detail[G01_016][data_val][]" value="<?php echo $G01_016['data_val0']; ?>" size="12" /></td>
    <td><input id="S30000737up" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737up"                  name="detail[G01_016][data_val][]" value="<?php echo $G01_016['data_val1']; ?>" size="12" /></td>
    <td><input id="S30000737bl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737bl"                  name="detail[G01_016][data_val][]" value="<?php echo $G01_016['data_val2']; ?>" size="12" /></td>
    <td><input id="S30000737bp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737bp"                  name="detail[G01_016][data_val][]" value="<?php echo $G01_016['data_val3']; ?>" size="12" /></td>
    <td><input id="S30000737kl" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737kl"                  name="detail[G01_016][data_val][]" value="<?php echo $G01_016['data_val4']; ?>" size="12" /></td>
    <td><input id="S30000737kp" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="S30000737kp"                  name="detail[G01_016][data_val][]" value="<?php echo $G01_016['data_val5']; ?>" size="12" /></td>
  </tr>
</table>