<table>
  <tr>
    <td width="24" bgcolor="purple" style='color:white'><div align="center"><strong>No</strong></div></td>
    <td width="550" bgcolor="purple" style='color:white'><div align="center"><strong> PROGRAM KESEHATAN USIA LANJUT</strong></div></td>
    <td colspan="2" bgcolor="purple" style='color:white'><div align="center"><strong>Yang Ada</strong></div></td>
    <td colspan="2" bgcolor="purple" style='color:white'><div align="center"><strong>Diperiksa</strong></div></td>
    </tr>
  <tr>
    <td bgcolor="#FFFFFF">1</td>
    <td bgcolor="#FFFFFF"> Umur 45-59 th (Pralansia)</td>
    <td width="48" bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000575yl" size="8" name="detail[H01_001][data_val][]" value="<?php echo $H01_001['data_val0']; ?>"/></td>
    <td width="48" bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000575yp" size="8" name="detail[H01_001][data_val][]" value="<?php echo $H01_001['data_val1']; ?>"/></td>
    <td width="48" bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000575dl" size="8" name="detail[H01_001][data_val][]" value="<?php echo $H01_001['data_val2']; ?>"/></td>
    <td width="48" bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000575dp" size="8" name="detail[H01_001][data_val][]" value="<?php echo $H01_001['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                       
  <tr>                                                                                                                                                                                                                                        
    <td bgcolor="#FFFFFF">2</td>                                                                                                                                                                                                              
    <td bgcolor="#FFFFFF">Umur 60-69 th (Lansia)</td>                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000576yl" size="8" name="detail[H01_002][data_val][]" value="<?php echo $H01_002['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000576yp" size="8" name="detail[H01_002][data_val][]" value="<?php echo $H01_002['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000576dl" size="8" name="detail[H01_002][data_val][]" value="<?php echo $H01_002['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000576dp" size="8" name="detail[H01_002][data_val][]" value="<?php echo $H01_002['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                       
  <tr>                                                                                                                                                                                                                                        
    <td bgcolor="#FFFFFF">3</td>                                                                                                                                                                                                              
    <td bgcolor="#FFFFFF"> Umur &gt; 70 th (Lansia Resti)</td>                                                                                                                                                                                
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000577yl" size="8" name="detail[H01_003][data_val][]" value="<?php echo $H01_003['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000577yp" size="8" name="detail[H01_003][data_val][]" value="<?php echo $H01_003['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000577dl" size="8" name="detail[H01_003][data_val][]" value="<?php echo $H01_003['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000577dp" size="8" name="detail[H01_003][data_val][]" value="<?php echo $H01_003['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td colspan="6">&nbsp;</td>                                                                                                                                                                                                              
    </tr>                                                                                                                                                                                                                                    
  <tr>                                                                                                                                                                                                                                       
    <td colspan="4" bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                            
    <td colspan="2" bgcolor="purple" style='color:white'><div align="center"><strong>Jumlah</strong></div></td>                                                                                                                              
    </tr>                                                                                                                                                                                                                                    
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">4</td>                                                                                                                                                                                                             
    <td colspan="3" bgcolor="#FFFFFF"> Jumlah lansia yang memiliki KMS</td>                                                                                                                                                                  
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000578l" size="8"  name="detail[H01_004][data_val][]" value="<?php echo $H01_004['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000578p" size="8"  name="detail[H01_004][data_val][]" value="<?php echo $H01_004['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">5</td>                                                                                                                                                                                                             
    <td colspan="3" bgcolor="#FFFFFF"> Jumlah lansia yang dirujuk ke PKM</td>                                                                                                                                                                
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000579l" size="8"  name="detail[H01_005][data_val][]" value="<?php echo $H01_005['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000579p" size="8"  name="detail[H01_005][data_val][]" value="<?php echo $H01_005['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">6</td>                                                                                                                                                                                                             
    <td colspan="3" bgcolor="#FFFFFF"> Jumlah lansia yang dirujuk ke RS</td>                                                                                                                                                                 
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000580l" size="8"  name="detail[H01_006][data_val][]" value="<?php echo $H01_006['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000580p" size="8"  name="detail[H01_006][data_val][]" value="<?php echo $H01_006['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">7</td>                                                                                                                                                                                                             
    <td colspan="3" bgcolor="#FFFFFF"> Jumlah Tingkat Kemandirian Lansia :</td>                                                                                                                                                              
    <td bgcolor="#FFFFFF"></td>                                                                                                                                                                                                              
    <td bgcolor="#FFFFFF"></td>                                                                                                                                                                                                              
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">a. Kemandirian A</td>                                                                                                                                                                                  
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000582l" size="8"  name="detail[H01_008][data_val][]" value="<?php echo $H01_008['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000582p" size="8"  name="detail[H01_008][data_val][]" value="<?php echo $H01_008['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">b. Kemandirian B</td>                                                                                                                                                                                  
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000583l" size="8"  name="detail[H01_009][data_val][]" value="<?php echo $H01_009['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000583p" size="8"  name="detail[H01_009][data_val][]" value="<?php echo $H01_009['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">c. Kemandirian C</td>                                                                                                                                                                                  
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000584l" size="8"  name="detail[H01_010][data_val][]" value="<?php echo $H01_010['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000584p" size="8"  name="detail[H01_010][data_val][]" value="<?php echo $H01_010['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">8</td>                                                                                                                                                                                                             
    <td colspan="3" bgcolor="#FFFFFF"> Status gizi lansia :</td>                                                                                                                                                                             
    <td bgcolor="#FFFFFF"></td>                                                                                                                                                                                                              
    <td bgcolor="#FFFFFF"></td>                                                                                                                                                                                                              
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">a. Lebih</td>                                                                                                                                                                                          
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000586l" size="8"  name="detail[H01_012][data_val][]" value="<?php echo $H01_012['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000586p" size="8"  name="detail[H01_012][data_val][]" value="<?php echo $H01_012['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">b. Normal</td>                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000587l" size="8"  name="detail[H01_013][data_val][]" value="<?php echo $H01_013['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000587p" size="8"  name="detail[H01_013][data_val][]" value="<?php echo $H01_013['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">c. Kurang</td>                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000588l" size="8"  name="detail[H01_014][data_val][]" value="<?php echo $H01_014['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000588p" size="8"  name="detail[H01_014][data_val][]" value="<?php echo $H01_014['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">9</td>                                                                                                                                                                                                             
    <td colspan="3" bgcolor="#FFFFFF">Tekanan Darah Lansia</td>                                                                                                                                                                              
    <td bgcolor="#FFFFFF"></td>                                                                                                                                                                                                              
    <td bgcolor="#FFFFFF"></td>                                                                                                                                                                                                              
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">a. Tinggi</td>                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000590l" size="8"  name="detail[H01_016][data_val][]" value="<?php echo $H01_016['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000590p" size="8"  name="detail[H01_016][data_val][]" value="<?php echo $H01_016['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">b. Normal</td>                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000591l" size="8"  name="detail[H01_017][data_val][]" value="<?php echo $H01_017['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000591p" size="8"  name="detail[H01_017][data_val][]" value="<?php echo $H01_017['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                        
    <td colspan="3" bgcolor="#FFFFFF">c. Rendah</td>                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000592l" size="8"  name="detail[H01_018][data_val][]" value="<?php echo $H01_018['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000592p" size="8"  name="detail[H01_018][data_val][]" value="<?php echo $H01_018['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                      
  <tr>                                                                                                                                                                                                                                       
    <td colspan="6">&nbsp;</td>                                                                                                                                                                                                              
    </tr>                                                                                                                                                                                                                                    
  <tr>                                                                                                                                                                                                                                       
    <td colspan="6" bgcolor="purple" style='color:white'><div align="center"><strong>PROGRAM KESEHATAN REMAJA</strong></div></td>                                                                                                            
    </tr>                                                                                                                                                                                                                                    
  <tr>                                                                                                                                                                                                                                       
    <td bgcolor="#FFFFFF">1</td>                                                                                                                                                                                                             
    <td colspan="3" bgcolor="#FFFFFF"> Jumlah Kunjungan Remaja Ke Puskesmas (10-19 th)</td>                                                                                                                                                  
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000593l" size="8"  name="detail[H01_019][data_val][]" value="<?php echo $H01_019['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000593p" size="8"  name="detail[H01_019][data_val][]" value="<?php echo $H01_019['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                                                               
  <tr>                                                                                                                                                                                                                                
    <td bgcolor="#FFFFFF">2</td>                                                                                                                                                                                                      
    <td bgcolor="purple" style='color:white'><div align="center"><strong>Jumlah Kasus Remaja Baru Yang Ditemui di Puskesmas/Luar Puskesmas</strong></div></td>                                                                        
    <td colspan="2" bgcolor="purple" style='color:white'><div align="center"><strong>Baru</strong></div></td>                                                                                                                         
    <td colspan="2" bgcolor="purple" style='color:white'><div align="center"><strong>Lama</strong></div></td>                                                                                                                         
    </tr>                                                                                                                                                                                                                             
  <tr>                                                                                                                                                                                                                                
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                 
    <td bgcolor="#FFFFFF"> a) Gangguan haid</td>                                                                                                                                                                                      
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000594bl" size="8" name="detail[H01_020][data_val][]" value="<?php echo $H01_020['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000594bp" size="8" name="detail[H01_020][data_val][]" value="<?php echo $H01_020['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000594ll" size="8" name="detail[H01_020][data_val][]" value="<?php echo $H01_020['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000594lp" size="8" name="detail[H01_020][data_val][]" value="<?php echo $H01_020['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                               
  <tr>                                                                                                                                                                                                                                
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                 
    <td bgcolor="#FFFFFF"> b) KTD (Kehamilan Tidak Diharapkan)</td>                                                                                                                                                                   
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000595bl" size="8" name="detail[H01_021][data_val][]" value="<?php echo $H01_021['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000595bp" size="8" name="detail[H01_021][data_val][]" value="<?php echo $H01_021['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000595ll" size="8" name="detail[H01_021][data_val][]" value="<?php echo $H01_021['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000595lp" size="8" name="detail[H01_021][data_val][]" value="<?php echo $H01_021['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                       
  <tr>                                                                                                                                                                                                                                        
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"> c) Abortus</td>                                                                                                                                                                                                    
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000596bl" size="8" name="detail[H01_022][data_val][]" value="<?php echo $H01_022['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000596bp" size="8" name="detail[H01_022][data_val][]" value="<?php echo $H01_022['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000596ll" size="8" name="detail[H01_022][data_val][]" value="<?php echo $H01_022['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000596lp" size="8" name="detail[H01_022][data_val][]" value="<?php echo $H01_022['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                       
  <tr>                                                                                                                                                                                                                                        
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"> d) Gangguan gizi</td>                                                                                                                                                                                              
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000597bl" size="8" name="detail[H01_023][data_val][]" value="<?php echo $H01_023['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000597bp" size="8" name="detail[H01_023][data_val][]" value="<?php echo $H01_023['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000597ll" size="8" name="detail[H01_023][data_val][]" value="<?php echo $H01_023['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000597lp" size="8" name="detail[H01_023][data_val][]" value="<?php echo $H01_023['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                       
  <tr>                                                                                                                                                                                                                                        
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"> e) HIV/AIDS</td>                                                                                                                                                                                                   
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000598bl" size="8" name="detail[H01_024][data_val][]" value="<?php echo $H01_024['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000598bp" size="8" name="detail[H01_024][data_val][]" value="<?php echo $H01_024['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000598ll" size="8" name="detail[H01_024][data_val][]" value="<?php echo $H01_024['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000598lp" size="8" name="detail[H01_024][data_val][]" value="<?php echo $H01_024['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                       
  <tr>                                                                                                                                                                                                                                        
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"> f) NAPZA</td>                                                                                                                                                                                                      
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000599bl" size="8" name="detail[H01_025][data_val][]" value="<?php echo $H01_025['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000599bp" size="8" name="detail[H01_025][data_val][]" value="<?php echo $H01_025['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000599ll" size="8" name="detail[H01_025][data_val][]" value="<?php echo $H01_025['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000599lp" size="8" name="detail[H01_025][data_val][]" value="<?php echo $H01_025['data_val3']; ?>"/></td>
  </tr>                                                                                                                                                                                                                                       
  <tr>                                                                                                                                                                                                                                        
    <td bgcolor="#FFFFFF">&nbsp;</td>                                                                                                                                                                                                         
    <td bgcolor="#FFFFFF"> g) Merokok</td>                                                                                                                                                                                                    
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000600bl" size="8" name="detail[H01_026][data_val][]" value="<?php echo $H01_026['data_val0']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000600bp" size="8" name="detail[H01_026][data_val][]" value="<?php echo $H01_026['data_val1']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000600ll" size="8" name="detail[H01_026][data_val][]" value="<?php echo $H01_026['data_val2']; ?>"/></td>
    <td bgcolor="#FFFFFF"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000600lp" size="8" name="detail[H01_026][data_val][]" value="<?php echo $H01_026['data_val3']; ?>"/></td>
  </tr>
</table>