<table>
  <tr>
    <td width="11" height="22" bgcolor="purple" style='color:white; padding:10px;'><div align="center">1</div></td>
    <td colspan="5" bgcolor="purple" style='color:white; padding:10px;'><div align="left"><strong>SEKOLAH</strong></div></td>
    <td bgcolor="purple" style='color:white; padding:10px;'><div align="center">Jumlah UKS</div></td>
    <td bgcolor="purple" style='color:white; padding:10px;'><div align="center">UKS dibina</div></td>
  </tr>
    <tr>
    <td width="11" height="22">&nbsp;</td>
    <td colspan="5">a. TK/RA</td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000601j" size="8" name="detail[I01_001][data_val][]" value="<?php echo $I01_001['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000601u" size="8" name="detail[I01_001][data_val][]" value="<?php echo $I01_001['data_val1']; ?>"/></td>
    </tr>                                                                                                                                                                                   
    <tr>                                                                                                                                                                                    
    <td width="11" height="22">&nbsp;</td>                                                                                                                                                  
    <td colspan="5">b. SD/MI</td>                                                                                                                                                           
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000602j" size="8" name="detail[I01_002][data_val][]" value="<?php echo $I01_002['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000602u" size="8" name="detail[I01_002][data_val][]" value="<?php echo $I01_002['data_val1']; ?>"/></td>
    </tr>                                                                                                                                                                                   
    <tr>                                                                                                                                                                                    
    <td width="11" height="22">&nbsp;</td>                                                                                                                                                  
    <td colspan="5">c. SMP/Sederajat</td>                                                                                                                                                   
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000603j" size="8" name="detail[I01_003][data_val][]" value="<?php echo $I01_003['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000603u" size="8" name="detail[I01_003][data_val][]" value="<?php echo $I01_003['data_val1']; ?>"/></td>
    </tr>                                                                                                                                                                                   
    <tr>                                                                                                                                                                                    
    <td width="11" height="22">&nbsp;</td>                                                                                                                                                  
    <td colspan="5">d. SMA/Sederajat</td>                                                                                                                                                   
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000604j" size="8" name="detail[I01_004][data_val][]" value="<?php echo $I01_004['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000604u" size="8" name="detail[I01_004][data_val][]" value="<?php echo $I01_004['data_val1']; ?>"/></td>
    </tr>                                                                                                                                                                                   
    <tr>                                                                                                                                                                                    
    <td width="11" height="22" bgcolor="purple" style='color:white; padding:10px;'>2</td>                                                                                                                                     
    <td colspan="5" bgcolor="purple" style='color:white; padding:10px;'><strong>SEKOLAH SEHAT</strong></td>                                                                                                                   
    <td bgcolor="purple" style='color:white; padding:10px;'><div align="center">Jumlah sekolah di wilayah puskesmas</div></td>                                                                                                
    <td bgcolor="purple" style='color:white; padding:10px;'><div align="center">Jumlah Sekolah Sehat</div></td>                                                                                                               
    </tr>                                                                                                                                                                                   
    <tr>                                                                                                                                                                                    
    <td width="11" height="22">&nbsp;</td>                                                                                                                                                  
    <td colspan="5">a. TK/RA</td>                                                                                                                                                           
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000605p" size="8" name="detail[I01_005][data_val][]" value="<?php echo $I01_005['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000605s" size="8" name="detail[I01_005][data_val][]" value="<?php echo $I01_005['data_val1']; ?>"/></td>
    </tr>                                                                                                                                                                                   
    <tr>                                                                                                                                                                                    
    <td width="11" height="22">&nbsp;</td>                                                                                                                                                  
    <td colspan="5">b. SD/MI</td>                                                                                                                                                           
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000606p" size="8" name="detail[I01_006][data_val][]" value="<?php echo $I01_006['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000606s" size="8" name="detail[I01_006][data_val][]" value="<?php echo $I01_006['data_val1']; ?>"/></td>
    </tr>                                                                                                                                                                                   
    <tr>                                                                                                                                                                                    
    <td width="11" height="22">&nbsp;</td>                                                                                                                                                  
    <td colspan="5">c. SMP/Sederajat</td>                                                                                                                                                   
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000607p" size="8" name="detail[I01_007][data_val][]" value="<?php echo $I01_007['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000607s" size="8" name="detail[I01_007][data_val][]" value="<?php echo $I01_007['data_val1']; ?>"/></td>
    </tr>                                                                                                                                                                                   
    <tr>                                                                                                                                                                                    
    <td width="11" height="22">&nbsp;</td>                                                                                                                                                  
    <td colspan="5">d. SMA/Sederajat</td>                                                                                                                                                   
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000608p" size="8" name="detail[I01_008][data_val][]" value="<?php echo $I01_008['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="" id="S30000608s" size="8" name="detail[I01_008][data_val][]" value="<?php echo $I01_008['data_val1']; ?>"/></td>
    </tr>                                                                                                                                                                          
    <tr>                                                                                                                                                                           
    <td height="22" colspan="8">&nbsp;</td>                                                                                                                                        
    </tr>                                                                                                                                                                          
                                                                                                                                                                                   
  <tr>                                                                                                                                                                             
    <td width="11" height="22" bgcolor="purple" style='color:white; padding:10px;'>3</td>                                                                                                                            
    <td colspan="5" bgcolor="purple" style='color:white; padding:10px;'><strong>Jumlah guru UKS yang mendapat pelatihan</strong></td>                                                                                
    <td bgcolor="purple" style='color:white; padding:10px;'><div align="center"><strong>L</strong></div></td>                                                                                                        
    <td bgcolor="purple" style='color:white; padding:10px;'><div align="center"><strong>P</strong></div></td>                                                                                                        
  </tr>                                                                                                                                                                            
  <tr>                                                                                                                                                                             
    <td height="23">&nbsp;</td>                                                                                                                                                    
    <td colspan="5">a. TK/RA</td>                                                                                                                                                  
    <td width="184"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000609l" size="8" name="detail[I01_009][data_val][]" value="<?php echo $I01_009['data_val0']; ?>"/></td>
    <td width="95"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000609p" size="8"  name="detail[I01_009][data_val][]" value="<?php echo $I01_009['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                            
  <tr>                                                                                                                                                                             
    <td height="23">&nbsp;</td>                                                                                                                                                    
    <td colspan="5">b. SD/MI</td>                                                                                                                                                  
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000610l" size="8"             name="detail[I01_010][data_val][]" value="<?php echo $I01_010['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000610p" size="8"             name="detail[I01_010][data_val][]" value="<?php echo $I01_010['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                            
  <tr>                                                                                                                                                                             
    <td height="23">&nbsp;</td>                                                                                                                                                    
    <td colspan="5">c. SMP/Sederajat</td>                                                                                                                                          
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000611l" size="8"             name="detail[I01_011][data_val][]" value="<?php echo $I01_011['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000611p" size="8"             name="detail[I01_011][data_val][]" value="<?php echo $I01_011['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                            
  <tr>                                                                                                                                                                             
    <td height="23">&nbsp;</td>                                                                                                                                                    
    <td colspan="5">d. SMA/Sederajat</td>                                                                                                                                          
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000612l" size="8"             name="detail[I01_012][data_val][]" value="<?php echo $I01_012['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000612p" size="8"             name="detail[I01_012][data_val][]" value="<?php echo $I01_012['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                            
  <tr>                                                                                                                                                                             
    <td height="21" colspan="8">&nbsp;</td>                                                                                                                      
    </tr>                                                                                                                                                                          
  <tr>                                                                                                                                                                             
    <td height="40">&nbsp;</td>                                                                                                                                                    
    <td width="222"><div align="left"><strong>Jumlah</strong></div></td>                                                                                                           
    <td colspan="2" bgcolor="#CCCCCC"><div align="center"><strong>Diwilayah Puskemas</strong></div></td>                                                                           
    <td colspan="2" bgcolor="#CCCCCC"><div align="center"><strong>Mendapat Pelatihan</strong></div></td>                                                                           
    <td colspan="2" bgcolor="#CCCCCC"><div align="center"><strong>Yang Dibina</strong></div></td>                                                                                  
    </tr>                                                                                                                                                                          
  <tr>                                                                                                                                                                             
    <td height="24">&nbsp;</td>                                                                                                                                                    
    <td>e. Dokter Kecil</td>                                                                                                                                                       
    <td width="57"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000613dl" size="8" name="detail[I01_013][data_val][]" value="<?php echo $I01_013['data_val0']; ?>"/></td>
    <td width="57"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000613dp" size="8" name="detail[I01_013][data_val][]" value="<?php echo $I01_013['data_val1']; ?>"/></td>
    <td width="56"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000613ml" size="8" name="detail[I01_013][data_val][]" value="<?php echo $I01_013['data_val2']; ?>"/></td>
    <td width="56"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000613mp" size="8" name="detail[I01_013][data_val][]" value="<?php echo $I01_013['data_val3']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000613yl" size="8"            name="detail[I01_013][data_val][]" value="<?php echo $I01_013['data_val4']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000613yp" size="8"            name="detail[I01_013][data_val][]" value="<?php echo $I01_013['data_val5']; ?>"/></td>
  </tr>                                                                                                                                                                            
  <tr>                                                                                                                                                                             
    <td height="24">&nbsp;</td>                                                                                                                                                    
    <td>f.  Kader Kesehatan Remaja</td>                                                                                                                                            
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000614dl" size="8"            name="detail[I01_014][data_val][]" value="<?php echo $I01_014['data_val0']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000614dp" size="8"            name="detail[I01_014][data_val][]" value="<?php echo $I01_014['data_val1']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000614ml" size="8"            name="detail[I01_014][data_val][]" value="<?php echo $I01_014['data_val2']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000614mp" size="8"            name="detail[I01_014][data_val][]" value="<?php echo $I01_014['data_val3']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="L" id="S30000614yl" size="8"            name="detail[I01_014][data_val][]" value="<?php echo $I01_014['data_val4']; ?>"/></td>
    <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="P" id="S30000614yp" size="8"            name="detail[I01_014][data_val][]" value="<?php echo $I01_014['data_val5']; ?>"/></td>
  </tr>
</table>