<table>
  <tr>
    <td width="16">1</td>
    <td width="500"> Jumlah Pelayanan Kasus Serumen Prop Anak Sekolah yang ditemukan</td>
    <td width="2"></td>
    <td width="11">:</td>
    <td width="468"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000630l" size="12"        name="detail[K03_001][data_val][]" value="<?php echo $K03_001['data_val0']; ?>"/>
      <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000630p" size="12"                 name="detail[K03_001][data_val][]" value="<?php echo $K03_001['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                  
 <tr>                                                                                                                                                                                    
    <td width="16">2</td>                                                                                                                                                                
    <td width="500">  Jumlah kasus tuli konginetal yang ditemukan</td>                                                                                                                   
    <td width="2"></td>                                                                                                                                                                  
    <td width="11">:</td>                                                                                                                                                                
    <td width="468"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000631l" size="12"        name="detail[K03_002][data_val][]" value="<?php echo $K03_002['data_val0']; ?>"/>
      <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000631p" size="12"                 name="detail[K03_002][data_val][]" value="<?php echo $K03_002['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                  
 <tr>                                                                                                                                                                                    
    <td width="16">3</td>                                                                                                                                                                
    <td width="500">    Jumlah kasus tuli konginetal yang dirujuk</td>                                                                                                                   
    <td width="2"></td>                                                                                                                                                                  
    <td width="11">:</td>                                                                                                                                                                
    <td width="468"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000632l" size="12"        name="detail[K03_003][data_val][]" value="<?php echo $K03_003['data_val0']; ?>"/>
        <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000632p" size="12"               name="detail[K03_003][data_val][]" value="<?php echo $K03_003['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                                  
 <tr>                                                                                                                                                                                    
   <td>4</td>                                                                                                                                                                            
   <td> Jumlah kasus Otitis Media Supuratif Kronis (OMSK) yang ditemukan</td>                                                                                                            
   <td></td>                                                                                                                                                                             
   <td>&nbsp;</td>                                                                                                                                                                       
   <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000633l" size="12"                     name="detail[K03_004][data_val][]" value="<?php echo $K03_004['data_val0']; ?>"/>
     <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000633p" size="12"                  name="detail[K03_004][data_val][]" value="<?php echo $K03_004['data_val1']; ?>"/></td>
 </tr>                                                                                                                                                                                   
 <tr>                                                                                                                                                                                    
   <td>5</td>                                                                                                                                                                            
   <td>Jumlah OMSK yang diobati</td>                                                                                                                                                     
   <td></td>                                                                                                                                                                             
   <td>&nbsp;</td>                                                                                                                                                                       
   <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000634l" size="12"                     name="detail[K03_005][data_val][]" value="<?php echo $K03_005['data_val0']; ?>"/>
     <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000634p" size="12"                  name="detail[K03_005][data_val][]" value="<?php echo $K03_005['data_val1']; ?>"/></td>
 </tr>                                                                                                                                                                                   
  <tr>                                                                                                                                                                                   
   <td>6</td>                                                                                                                                                                            
   <td>Jumlah OMSK yang dirujuk</td>                                                                                                                                                     
   <td></td>                                                                                                                                                                             
   <td>&nbsp;</td>                                                                                                                                                                       
   <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000635l" size="12"                     name="detail[K03_006][data_val][]" value="<?php echo $K03_006['data_val0']; ?>"/>
     <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000635p" size="12"                  name="detail[K03_006][data_val][]" value="<?php echo $K03_006['data_val1']; ?>"/></td>
 </tr>                                                                                                                                                                                   
 <tr>                                                                                                                                                                                    
   <td>7</td>                                                                                                                                                                            
   <td>Jumlah penyakit telinga lainnya yang ditemukan</td>                                                                                                                               
   <td></td>                                                                                                                                                                             
   <td>&nbsp;</td>                                                                                                                                                                       
   <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000753l" size="12"                     name="detail[K03_007][data_val][]" value="<?php echo $K03_007['data_val0']; ?>"/>
     <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000753p" size="12"                  name="detail[K03_007][data_val][]" value="<?php echo $K03_007['data_val1']; ?>"/></td>
 </tr>
 </table>