<table>
  <tr>
    <td width="16">1</td>
    <td width="700">  Jumlah kelompok masyarakat (UKBM) yang melakukan upaya penemuan dini dan rujukan kesehatan jiwa</td>
    <td width="0"></td>
    <td width="3">:</td>
    <td width="394"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000636l" size="12"                                                name="detail[K04_001][data_val][]" value="<?php echo $K04_001['data_val0']; ?>"/>
      <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000636p" size="12"                                                         name="detail[K04_001][data_val][]" value="<?php echo $K04_001['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                          
 <tr>                                                                                                                                                                            
    <td width="16">2</td>                                                                                                                                                        
    <td width="700">   Jumlah penemuan dan penanganan kasus gangguan perilaku, jiwa, Napza dll yang dirujuk oleh Kader/Masy.</td>                                                
    <td width="0"></td>                                                                                                                                                          
    <td width="3">:</td>                                                                                                                                                         
    <td width="394"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000637l" size="12"                                                name="detail[K04_002][data_val][]" value="<?php echo $K04_002['data_val0']; ?>"/>
      <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000637p" size="12"                                                         name="detail[K04_002][data_val][]" value="<?php echo $K04_002['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                          
 <tr>                                                                                                                                                                            
    <td width="16">3</td>                                                                                                                                                        
    <td width="700">     Jumlah kasus kesehatan jiwa yang dirujuk ke RS/Dokter Spesialis</td>                                                                                    
    <td width="0"></td>                                                                                                                                                          
    <td width="3">:</td>                                                                                                                                                         
    <td width="394"><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000638l" size="12"                                                name="detail[K04_003][data_val][]" value="<?php echo $K04_003['data_val0']; ?>"/>
      <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000638p" size="12"                                                         name="detail[K04_003][data_val][]" value="<?php echo $K04_003['data_val1']; ?>"/></td>
  </tr>                                                                                                                                                                          
 <tr>                                                                                                                                                                            
   <td>4</td>                                                                                                                                                                    
   <td> Deteksi dan penanganan kasus jiwa (gangguan perilaku, jiwa,psikosomatis,Napza,dll) yang berobat ke puskesmas</td>                                                        
   <td></td>                                                                                                                                                                     
   <td>:</td>                                                                                                                                                               
   <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000639l" size="12"                                                            	name="detail[K04_004][data_val][]" value="<?php echo $K04_004['data_val0']; ?>"/>
     <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000639p" size="12"                                                           name="detail[K04_004][data_val][]" value="<?php echo $K04_004['data_val1']; ?>"/></td>
 </tr>                                                                                                                                                                           
 <tr>                                                                                                                                                                            
   <td>5</td>                                                                                                                                                                    
   <td> Jumlah kunjungan kasus gangguan jiwa</td>                                                                                                                                
   <td></td>                                                                                                                                                                     
   <td>:</td>                                                                                                                                                               
   <td><input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Laki" id="S30000640l" size="12"                                                            	name="detail[K04_005][data_val][]" value="<?php echo $K04_005['data_val0']; ?>"/>
     <input type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' placeholder="Perempuan" id="S30000640p" size="12"                                                           name="detail[K04_005][data_val][]" value="<?php echo $K04_005['data_val1']; ?>"/></td>
 </tr>
</table>