<table width="80%" border="1" cellpadding="2" cellspacing="0" bordercolor="#CCCCCC">
  <tr>
    <td rowspan="4" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>No</strong></div></td>
    <td colspan="10" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>PELAYANAN BPJS</strong></div></td>
    </tr>
  <tr>
    <td colspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>JUMLAH KUNJUNGAN</strong></div></td>
    <td colspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>JENIS KELAMIN</strong></div></td>
    <td colspan="6" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>PENERIMA YANKES</strong></div></td>
    </tr>
  <tr>
    <td bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>Rawat Jalan</strong></div></td>
    <td bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>Rawat Inap</strong></div></td>
    <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>Laki-Laki</strong></div></td>
    <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>Perempuan</strong></div></td>
    <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>&lt; 1 Th</strong></div></td>
    <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>1- 4 Th</strong></div></td>
    <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>5 - 14 Th</strong></div></td>
    <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>15 - 44 Th</strong></div></td>
    <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>45 - 64 Th</strong></div></td>
    <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>65 + Th</strong></div></td>
  </tr>
  <tr>
    <td bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>(Kunjungan)</strong></div></td>
    <td bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>(Orang)</strong></div></td>
    </tr>
  <tr>
    <td height="45"><div align="center">1</div></td>
    <td><div align="center"><input id="t1brj" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val0'];  	?>"                                                                                                                                   size="6" /></div></td>
    <td><div align="center"><input id="t1bri" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val1'];  	?>"                                                                                                                                   size="6" />
    </div></td>                                                                                                                                                                                                                                                                                 
    <td><div align="center"><input type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="t1bl" size="6" name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val2'];  ?>"                                                                                                                                   /></div></td>
    <td><div align="center"><input type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="t1bp" size="6" name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val3'];  ?>"                                                                                                                                  /></div></td>
    <td><div align="center"><input type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="t1b1" size="6" name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val4'];  ?>"                                                                                                                                  /></div></td>
    <td><div align="center"><input type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="t1b4" size="6" name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val5'];  ?>"                                                                                                                                  /></div></td>
    <td><div align="center"><input type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="t1b14" size="6" name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val6'];  	?>"                                                                                                                                  /></div></td>
    <td><div align="center"><input type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="t1b44" size="6" name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val7'];  	?>"                                                                                                                                  /></div></td>
    <td><div align="center"><input type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="t1b64" size="6" name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val8'];  	?>"                                                                                                                                  /></div></td>
    <td><div align="center"><input type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' id="t1b65" size="6" name="detail[L03_001][data_val][]" value="<?php echo $L03_001['data_val9'];  	?>"                                                                                                                                  /></div></td>
  </tr>                                                                                                                                                                                                                                                                                         
</table>                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                
      <p>&nbsp;</p>                                                                                                                                                                                                                                                                             
      <table width="80%" border="1" cellpadding="2" cellspacing="0" bordercolor="#CCCCCC">                                                                                                                                                                                                      
        <tr>                                                                                                                                                                                                                                                                                    
          <td rowspan="4" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>No</strong></div></td>                                                                                                                                                                 
          <td colspan="10" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>PELAYANAN KARTU SEHAT</strong></div></td>                                                                                                                                             
        </tr>                                                                                                                                                                                                                                                                                   
        <tr>                                                                                                                                                                                                                                                                                    
          <td colspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>JUMLAH KUNJUNGAN</strong></div></td>                                                                                                                                                   
          <td colspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>JENIS KELAMIN</strong></div></td>                                                                                                                                                      
          <td colspan="6" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>PENERIMA YANKES</strong></div></td>                                                                                                                                                    
        </tr>                                                                                                                                                                                                                                                                                   
        <tr>                                                                                                                                                                                                                                                                                    
          <td bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>Rawat Jalan</strong></div></td>                                                                                                                                                                    
          <td bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>Rawat Inap</strong></div></td>                                                                                                                                                                     
          <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>Laki-Laki</strong></div></td>                                                                                                                                                          
          <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>Perempuan</strong></div></td>                                                                                                                                                          
          <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>&lt; 1 Th</strong></div></td>                                                                                                                                                          
          <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>1- 4 Th</strong></div></td>                                                                                                                                                            
          <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>5 - 14 Th</strong></div></td>                                                                                                                                                          
          <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>15 - 44 Th</strong></div></td>                                                                                                                                                         
          <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>45 - 64 Th</strong></div></td>                                                                                                                                                         
          <td rowspan="2" bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>65 + Th</strong></div></td>                                                                                                                                                            
        </tr>                                                                                                                                                                                                                                                                                   
        <tr>                                                                                                                                                                                                                                                                                    
          <td bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>(Kunjungan)</strong></div></td>                                                                                                                                                                    
          <td bgcolor="purple" style='padding:3px; color:white' ><div align="center"><strong>(Orang)</strong></div></td>                                                                                                                                                                        
        </tr>                                                                                                                                                                                                                                                                                   
        <tr>                                                                                                                                                                                                                                                                                    
          <td height="44"><div align="center">1</div></td>                                                                                                                                                                                                                                      
            <td><div align="center"><input id="t1krj" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L03_002][data_val][]"  value="<?php echo $L03_002['data_val0'];  	?>"                                                                                                                                size="6" /></div></td>
    <td><div align="center">                                                                                                                                                                                       	                                                         
      <input id="t1kri" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val1']; ?>" size="6" />
    </div></td>                                                                                                                                                                                                                                                                
    <td><div align="center"><input id="t1kl" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();'  name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val2'];  ?>"                                                                                                                                size="6" /></div></td>
    <td><div align="center"><input id="t1kp" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();'  name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val3'];  ?>"                                                                                                                                size="6" /></div></td>
    <td><div align="center"><input id="t1k1" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();'  name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val4'];  ?>"                                                                                                                                size="6" /></div></td>
    <td><div align="center"><input id="t1k4" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();'  name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val5'];  	?>"                                                                                                                              size="6" /></div></td>
    <td><div align="center"><input id="t1k14" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val6'];  	?>"                                                                                                                                size="6" /></div></td>
    <td><div align="center"><input id="t1k44" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val7'];  	?>"                                                                                                                                size="6" /></div></td>
    <td><div align="center"><input id="t1k64" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val8'];  	?>"                                                                                                                              size="6" /></div></td>
    <td><div align="center"><input id="t1k65" type="text" <?=$dis;?> class="input-sm" size='10' style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L03_002][data_val][]" value="<?php echo $L03_002['data_val9'];  	?>"                                                                                                                              size="6" /></div></td>
        </tr>
</table>