<table width="80%" border="0" cellpadding="2" cellspacing="0">
          <tr>
            <td width="63" rowspan="3" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">No</div></td>
            <td width="471" rowspan="3" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">ASAL KELUHAN</div></td>
            <td colspan="4" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">JENIS KELUHAN</div></td>
          </tr>
          <tr>
            <td colspan="2" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">Administrasi</div></td>
            <td colspan="2" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">Pelayanan Kesehatan</div></td>
          </tr>
          <tr>
            <td width="80" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">Jumlah</div></td>
            <td width="80" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">Tertangani</div></td>
            <td width="80" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">Jumlah</div></td>
            <td width="80" bgcolor="purple" style='padding:3px; color:white;'><div align="center" class="style1">Tertangani</div></td>
          </tr>
          <tr>
            <td>I</td>
            <td>PESERTA BPJS</td>
            <td width="80"><div align="center">
              <input  id="b1aj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();'   name="detail[L04_001][data_val][]" value="<?php echo $L04_001['data_val0'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                                          
            <td width="80"><div align="center">                                                                                                                                                                                                                  
              <input  id="b1at" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();'   name="detail[L04_001][data_val][]" value="<?php echo $L04_001['data_val1'];  ?>"                                                                                                                                                                             size="5" />
</div></td>                                                                                                                                                                                                                                                      
            <td width="80"><div align="center">                                                                                                                                                                                                                  
              <input  id="b1pj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();'   name="detail[L04_001][data_val][]" value="<?php echo $L04_001['data_val2'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                                          
            <td width="80"><div align="center">                                                                                                                                                                                                                  
              <input  id="b1pt" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();'   name="detail[L04_001][data_val][]" value="<?php echo $L04_001['data_val3'];  ?>"                                                                                                                                                                             size="5" />
</div></td>                                                                                                                                                                                                                                                      
          </tr>                                                                                                                                                                                                                                  
          <tr>                                                                                                                                                                                                                                   
            <td>II</td>                                                                                                                                                                                                                          
            <td>PPK</td>                                                                                                                                                                                                                         
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="b2aj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_002][data_val][]" value="<?php echo $L04_002['data_val0'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="b2at" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_002][data_val][]" value="<?php echo $L04_002['data_val1'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="b2pj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_002][data_val][]" value="<?php echo $L04_002['data_val2'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="b2pt" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_002][data_val][]" value="<?php echo $L04_002['data_val3'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
          </tr>                                                                                                                                                                                                                                  
          <tr>                                                                                                                                                                                                                                   
            <td>III</td>                                                                                                                                                                                                                         
            <td>PEMERHATI</td>                                                                                                                                                                                                                   
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="b3aj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_003][data_val][]" value="<?php echo $L04_003['data_val0'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="b3at" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_003][data_val][]" value="<?php echo $L04_003['data_val1'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="b3pj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_003][data_val][]" value="<?php echo $L04_003['data_val2'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="b3pt" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_003][data_val][]" value="<?php echo $L04_003['data_val3'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
          </tr>                                                                                                                                                                                                                                  
          <tr>                                                                                                                                                                                                                                   
            <td colspan="6">&nbsp;</td>                                                                                                                                                                                                          
          </tr>                                                                                                                                                                                                                                  
          <tr>                                                                                                                                                                                                                                   
            <td>I</td>                                                                                                                                                                                                                           
            <td>PESERTA KARTU SEHAT</td>                                                                                                                                                                                                         
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k1aj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_004][data_val][]" value="<?php echo $L04_004['data_val0'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k1at" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_004][data_val][]" value="<?php echo $L04_004['data_val1'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k1pj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_004][data_val][]" value="<?php echo $L04_004['data_val2'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k1pt" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_004][data_val][]" value="<?php echo $L04_004['data_val3'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
          </tr>                                                                                                                                                                                                                                  
          <tr>                                                                                                                                                                                                                                   
            <td>II</td>                                                                                                                                                                                                                          
            <td>PPK</td>                                                                                                                                                                                                                         
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k2aj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_005][data_val][]" value="<?php echo $L04_005['data_val0'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k2at" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_005][data_val][]" value="<?php echo $L04_005['data_val1'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k2pj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_005][data_val][]" value="<?php echo $L04_005['data_val2'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k2pt" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_005][data_val][]" value="<?php echo $L04_005['data_val3'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
          </tr>                                                                                                                                                                                                                                  
          <tr>                                                                                                                                                                                                                                   
            <td>III</td>                                                                                                                                                                                                                         
            <td>PEMERHATI</td>                                                                                                                                                                                                                   
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k3aj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_006][data_val][]" value="<?php echo $L04_006['data_val0'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k3at" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_006][data_val][]" value="<?php echo $L04_006['data_val1'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k3pj" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_006][data_val][]" value="<?php echo $L04_006['data_val2'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
            <td><div align="center">                                                                                                                                                                                                             
                <input  id="k3pt" type="text" <?=$dis;?> class="input-sm" style='margin:3px;' onkeypress='this.value=ignoreSpaces(this.value); return NumOnly(event);' onkeyup='javascript:this.value = this.value.toUpperCase();' name="detail[L04_006][data_val][]" value="<?php echo $L04_006['data_val3'];  ?>"                                                                                                                                                                             size="5" />
            </div></td>                                                                                                                                                                                                                          
          </tr>                                                                                                                                                                                                                                  
</table>                                                                                                                                                                                                                                         